version: "2.3"
services:
  mysql:
    container_name: mysql_testing
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_USER=testing
      - MYSQL_PASSWORD=testing-pass
      - MYSQL_ROOT_PASSWORD=root-pass
  redis:
    container_name: redis_testing
    image: redis:5.0.2-alpine
    ports:
      - 6379:6379
